import { Poppins } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/provider/TanstackProvider";
import { Toaster } from "react-hot-toast";
import ReduxProviderWrapper from "@/provider/ReduxProvider";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Chatterbox",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={`${poppins.className} bg-blue-100`}>
          <Toaster/>
          <TanstackProvider><ReduxProviderWrapper>{children} </ReduxProviderWrapper></TanstackProvider>
      </body>
    </html>
  );
}
